# Настройки подключения к базе, можно указать SQLITE, если MYSQL не нужен
database:
  type: MYSQL
  hostname: 127.0.0.1
  port: 3306
  database: common_test
  username: "root"
  password: ""

# Время обновления постов в вк в секундах
# Проще говоря, как часто будет выводиться сообщение о новом посте, если он появился
updateTime: 30

# Настройка данных группы ВК
vkGroup:
  # Токен приложения, которое будет получать посты
  accessToken: "d6180d97d6180d97d6180d977bd66106bcdd618d6180d97b73a3a80da7159d6d2eba372"

  # Здесь необходимо указать либо домен, либо айди группы
  # В приоритете используется домен, если домен не указан или указан как "null", то используется id
  domain: "moonstudio"
  id: 1